# Mobb/Snyk Fixer on pull requests
# This workflow defines the needed steps to run Snyk Code on every pull request and pass the results to Mobb Fixer.
#
# Secrets in use:
# SNYK_API_TOKEN - your Snyk user credentials (find how to get it here: https://docs.snyk.io/getting-started/how-to-obtain-and-authenticate-with-your-snyk-api-token)
# MOBB_API_TOKEN - your mobb user credentials (autumatially set if you forked this repo via the Mobb app)
# GITHUB_TOKEN - automatically set by GitHub

on: [pull_request]
permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to get code
        uses: actions/checkout@v3
      - name: Run SAST scan
        run:
          npx snyk auth ${{ secrets.SNYK_API_KEY }}
          
          npx snyk code test --sarif-file-output=/home/runner/report.json ./
          
        shell: bash -l {0}
      - name: Run Mobb on the findings and get fixes
        if: failure()
        uses: mobb-dev/action@beta0.0.4
        with:
          report-file: "/home/runner/report.json"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scanner: snyk
